FROM node:20.11.1-alpine3.19
# Set working directory inside container
USER root
WORKDIR /app
# Copy package.json & package-lock.json
COPY package.json package-lock.json ./

RUN npm install

CMD ["npm","run","start:dev"]

