FROM nginx:mainline-alpine3.18-perl
ARG NGINX_HOST
ARG IS_FOR_VERIFICATION
COPY nginx.prod.conf /etc/nginx/nginx.prod.conf
COPY nginx.verification.conf /etc/nginx/nginx.verification.conf

RUN if [ "$IS_VERIFICATION" = "no" ]; then \
        cat /etc/nginx/nginx.prod.conf > /etc/nginx/nginx.conf; \
    else \
        cat /etc/nginx/nginx.verification.conf > /etc/nginx/nginx.conf; \
    fi

RUN sed -i "s/\${NGINX_HOST}/${NGINX_HOST}/g" /etc/nginx/nginx.conf