FROM node:20.11.1-alpine3.19
# Set working directory inside container
USER root
WORKDIR /ui
# Copy package.json & package-lock.json
COPY package.json package-lock.json ./
# Install dev + prod dependencies
RUN npm install
# Start Server
CMD ["npm","run","dev"]